[project]
name = "fluxrt"
version = "1.0"
requires-python = ">=3.12"
dependencies = [
    "transformers",
    "torchaudio @ https://download.pytorch.org/whl/cu128/torchaudio-2.11.0%2Bcu128-cp312-cp312-manylinux_2_28_x86_64.whl",
    "diffusers",
    "numpy<2.3",
    "nvidia-riva-client>=2.26.0",
    "scipy>=1.10,<1.14",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
